version: '2'
services:
  cassandra:
    image: cassandra
    ports:
     - '7000:7000'
     - '9042:9042'
    volumes:
     - db:/var/lib/cassandra
     - ./cassandra-init.sh:/cassandra-init.sh
    command: "sh /cassandra-init.sh"
    environment:
     - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
  elastic:
    image: elasticsearch:6.5.1
    ports:
     - '9200:9200'
     - '9300:9300'
    volumes:
      - es:/usr/share/elasticsearch/data
    network_mode: "host"
    environment:
      - discovery.type=single-node
volumes:
  db:
    external: true
  es:
    external: true

