version: '2'
services:
  cassandra:
    image: cassandra
    ports:
     - '7000:7000'
     - '9042:9042'
    volumes:
     - db:/var/lib/cassandra
    environment:
     - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
volumes:
  db:
    external: true